// next
import Head from 'next/head'


// styles
import styles from '../styles/index.module.scss'


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=''>
                
                <div className=''>
                    <h1>Main </h1>
                    <h1>Main </h1>
                    <h1>Main </h1>
                    <h1>Main </h1>
                    <h1>MainMainMainMainMainMainMain </h1>
                </div>
            </main>
        </>
    )
}
