// next
import Head from 'next/head'
import React from 'react';

// styles
import { PageConfig } from '@/styles/PagesConfigElements';

// components
import Dashboard from '@/components/dashboard/dashboard';
import StudentFrom from '@/components/formCRUD/StudentFrom';


export default function Home() {


    return (
        <>
            <Head>
                <title>VUZF Students</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <PageConfig>
                    <h1>index</h1>
                    <StudentFrom />
                    {/* <Dashboard /> */}
                </PageConfig>
            </main>
        </>
    )
}